server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://39.106.46.89:3306/mg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/mg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  redis:
    port: 6379
    host: 39.106.46.89
    #    host: 127.0.0.1
    database: 0 #Redis数据库索引（默认为0）
    timeout: 1800000  #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
aliyun:
  endpoint: http://oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI5t6jZX3snWx9vjeC1VG2
  accessKeySecret: ay4MaA4XYjJKS7hRVaPYR7H8vDnXSw
  bucketName: mingge-blog1
  aaurl: https://mingge-blog1.oss-cn-chengdu.aliyuncs.com/
