server:
  port: 8989
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.46.89:3306/mg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/mg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  main:
    allow-circular-references: true


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
aliyun:
  endpoint: http://oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI5t6jZX3snWx9vjeC1VG2
  accessKeySecret: ay4MaA4XYjJKS7hRVaPYR7H8vDnXSw
  bucketName: mingge-blog1
  aaurl: https://mingge-blog1.oss-cn-chengdu.aliyuncs.com/